### ISSUE TITLE
If a user has dtrace installed already, can we continue without building dtrace?

### ISSUE THREAD

**Issue by dilawar** [SubconsciousCompute/libdtrace-rs#1]

**Comment by cyberphantom52** [comment]
We still need `dtrace.lib` in order to link at compile time. This is generated only when building dtrace

**Comment by dilawar** [comment]
Won't it work with the shared library `dtrace.dll` if static is not there? 

![image](https://github.com/SubconsciousCompute/libdtrace-rs/assets/895681/eddbe31a-d359-4204-bbc0-c7887f42d938)

## Drivers

![image](https://github.com/SubconsciousCompute/libdtrace-rs/assets/895681/16c122ed-8b84-4ac2-9c42-767d6cae84ab)

**Comment by cyberphantom52** [comment]
That's what i tried initially but couldn't get it to work. I'll do some more testing and see if i can come up with something.


PS: We still need the header definitions from dtrace and we're not building all of dtrace, just the library so it shouldn't matter too much. Also the end user only needs to have dtrace kernel driver installed. All of the other dependencies are compile time only.
